---
- name: Generate secure boot signing keys
  listen: Generate Keys
  shell: |
    openssl req -new -x509 -nodes -newkey rsa:2048 -keyout /var/lib/shim-signed/mok/MOK.priv -outform DER -out /var/lib/shim-signed/mok/MOK.der -days 36500 -subj "/CN=lab.astr0rack.net"
    openssl x509 -inform der -in /var/lib/shim-signed/mok/MOK.der -out /var/lib/shim-signed/mok/MOK.pem
    mokutil --import /var/lib/shim-signed/mok/MOK.der

- name: Sign current kernel with signing keys (if this fails there will be pain)
  listen: Generate Keys
  shell: |
    VERSION="$(uname -r)"
    SHORT_VERSION="$(uname -r | cut -d . -f 1-2)"
    MODULES_DIR=/lib/modules/$VERSION
    KBUILD_DIR=/usr/lib/linux-kbuild-$SHORT_VERSION
    sbsign --key MOK.priv --cert MOK.pem "/boot/vmlinuz-$VERSION" --output "/boot/vmlinuz-$VERSION.tmp"
    mv "/boot/vmlinuz-$VERSION.tmp" "/boot/vmlinuz-$VERSION"

- name: Restart pveproxy
  listen: Restart pveproxy
  ansible.builtin.systemd:
    name: pveproxy.service
    state: restarted

- name: Restart guest nics
  listen: Restart guest nics
  shell: ifreload -a
 
