---
- name: Configure name servers
  vyos.vyos.vyos_system:
    name_servers:
      - 1.1.1.1
      - 1.0.0.1

- name: Configure domain search suffixes
  vyos.vyos.vyos_system:
    domain_search:
      - lab.astr0rack.net

- name: Configure hostname and domain-name
  vyos.vyos.vyos_system:
    host_name: vyos-core
    domain_name: lab.astr0rack.net

- name: Configure default route
  vyos.vyos.vyos_config:
    lines:
      - set protocols static route 0.0.0.0/0 dhcp-interface 'eth0'

- name: Configure ntp
  vyos.vyos.vyos_config:
    lines:
      - set service ntp server 192.168.55.1 prefer
      - set service ntp listen-address 0.0.0.0
      - set service ntp allow-client address 10.0.0.0/16

- name: Set facts for ansible ssh
  ansible.builtin.set_fact:
    ansible_connection: ssh
    ansible_user: vyos

- name: Copy discord notify script
  ansible.builtin.template:
    src: discord-init.sh
    dest: /config/user-data/
    mode: "0755"

- name: Enable discord notify script
  ansible.builtin.lineinfile:
    path: '/config/scripts/vyos-postconfig-bootup.script'
    regexp: '^/config/user-data/discord-init.sh'
    line: '/config/user-data/discord-init.sh &1>/dev/null'

- name: Set facts for network connection
  ansible.builtin.set_fact:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: vyos.vyos.vyos
    ansible_user: vyos
