---
- name: Include secrets from environment
  ansible.builtin.include_tasks:
    file: env.yml
    apply:
      tags:
        - env
  tags:
    - env
    - never
- name: Include secrets from bitwarden
  ansible.builtin.include_tasks:
    file: bw.yml
    apply:
      tags:
        - bw
  tags:
    - bw
    - never
- name: Apply general setup and hardening
  ansible.builtin.include_tasks:
    file: general_setup.yml
    apply:
      tags:
        - setup
  tags:
    - setup
- name: Configure DNS Setup
  ansible.builtin.include_tasks:
    file: dns_setup.yml
    apply:
      tags:
        - dns
  tags:
    - dns
- name: Configure Tailscale
  ansible.builtin.include_tasks:
    file: tailscale_setup.yml
    apply:
      tags:
        - tailscale
  tags:
    - tailscale
- name: Configure Interfaces
  ansible.builtin.include_tasks:
    file: interfaces.yml
    apply:
      tags:
        - interfaces
  tags:
    - interfaces
- name: Configure DHCP
  ansible.builtin.include_tasks:
    file: dhcp.yml
    apply:
      tags:
        - dhcp
  tags:
    - dhcp
- name: Configure Outbound NAT
  ansible.builtin.include_tasks:
    file: nat.yml
    apply:
      tags:
        - nat
  tags:
    - nat
- name: Configure Firewall
  ansible.builtin.include_tasks:
    file: firewall.yml
    apply:
      tags:
        - firewall
  tags:
    - firewall
- name: Save Configuration
  ansible.builtin.include_tasks:
    file: save.yml
    apply:
      tags:
        - always
  tags:
    - always
