---
- name: "configure DHCP Static Mappings: {{ interface.desc }}"
  vyos.vyos.vyos_config:
    lines:
      - "set service dhcp-server shared-network-name {{ interface.desc }} subnet {{ interface.dhcp.subnet }} static-mapping {{ item.name }} mac-address '{{ item.mac }}'"
      - "set service dhcp-server shared-network-name {{ interface.desc }} subnet {{ interface.dhcp.subnet }} static-mapping {{ item.name }} ip-address '{{ item.ipv4 }}'"
  loop: "{{ interface.dhcp.static_mappings }}"

