---
- name: Check tailscale status
  vyos.vyos.vyos_command:
    commands:
      - tailscale status
  register: tailscale_status

- name: Login to tailscale and start
  vyos.vyos.vyos_command:
    commands:
      - "sudo tailscale login --auth-key={{ tailscale_auth_key }}"
      - "sudo tailscale up --advertise-routes=10.0.0.0/16,192.168.55.2/32,192.168.55.3/32"
  when: tailscale_status.stdout is search('Logged out')
