version: '3.4'

services:
  postgres:
    container_name: postgres
    image: docker.io/library/postgres:15
    restart: unless-stopped
    security_opt:
    - apparmor:unconfined
    command: >
      -c ssl=on 
      -c ssl_cert_file=/certs/caddy/certificates/acme-v02.api.letsencrypt.org-directory/postgres.lab.astr0rack.net/postgres.lab.astr0rack.net.crt
      -c ssl_key_file=/certs/caddy/certificates/acme-v02.api.letsencrypt.org-directory/postgres.lab.astr0rack.net/postgres.lab.astr0rack.net.key
    environment:
      POSTGRES_USER: terraform
      POSTGRES_DB: terraform
      POSTGRES_PASSWORD: {{ postgres_password }}
    volumes:
      - "postgres_data_vol:/var/lib/postgresql/data"
      - "caddy_data_vol:/certs:ro"
    ports:
      - "5432:5432"

volumes:
  caddy_data_vol:
    external: true
  postgres_data_vol:
    external: true

