version: '3.4'

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_NOTIFICATION_URL: "discord://{{ watchtower_webhook_url }}"
      WATCHTOWER_CLEANUP: "true"
