---
users:
  - name: vyos
    pw_hash: "{{ vyos_user_hash }}"
    public_keys:
      - name: astr0n8t@primary.yubikey
        type: sk-ssh-ed25519@openssh.com
        key: AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIFEhLIyleqCaN3lEJ77AYc/q1uZlqsDJ4PKhBu0dXUa7AAAABHNzaDo=
      - name: astr0n8t@secondary.yubikey
        type: sk-ssh-ed25519@openssh.com
        key: AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIHKBaozeIJ+Gz7+J2dK2VrQPaWerVWH8a9xYIjhvygLmAAAABHNzaDo=
      - name: astr0n8t@mobile
        type: ecdsa-sha2-nistp256
        key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGwVUk4wWGiJQjd7P2z2XZ9Gzia0GTy2faoAnyWVEF+jweR2q16C75oIzZbgE1mN3oc4BD9z8rIA1ElX
      - name: ghactions@github.com
        type: ssh-ed25519
        key: AAAAC3NzaC1lZDI1NTE5AAAAIH8ts84bR4nen8+Kk6I48MDkg8WA+gnuoUFuCmG9B6Xg
interfaces:
  - name: eth0
    type: ethernet
    desc: Rack
    mac: 92:07:2b:55:57:c8
    ipv4_addr: dhcp
    zone: external-rack
  - name: eth1
    type: ethernet
    desc: LABDC
    mac: aa:06:c0:1f:48:d1
    ipv4_addr: 10.0.0.1/24
    dhcp:
      subnet: 10.0.0.0/24
      gw: 10.0.0.1
      dns_servers:
        - 10.0.0.1
      domain_name: lab.astr0rack.net
      start: 10.0.0.100
      stop: 10.0.0.200
      static_mappings:
        - name: dc-01
          mac: 22:ca:a4:90:bb:04
          ipv4: 10.0.0.50
        - name: dc-02
          mac: ea:87:14:1a:6d:7f
          ipv4: 10.0.0.51
  - name: eth2
    type: ethernet
    desc: LABDMZ
    mac: a6:7e:41:70:6b:ca
    ipv4_addr: 10.0.10.1/24
    dhcp:
      subnet: 10.0.10.0/24
      gw: 10.0.10.1
      dns_servers:
        - 10.0.10.1
      domain_name: lab.astr0rack.net
      start: 10.0.10.100
      stop: 10.0.10.200
      static_mappings:
        - name: dns-01
          mac: 36:aa:9e:ec:02:de
          ipv4: 10.0.10.10
        - name: web-01
          mac: 92:65:8b:40:2a:7e
          ipv4: 10.0.10.20
  - name: eth3
    type: ethernet
    desc: LABLAN
    mac: ba:e1:dc:d6:d5:80
    ipv4_addr: 10.0.20.1/24
    dhcp:
      subnet: 10.0.20.0/24
      gw: 10.0.20.1
      dns_servers:
        - 10.0.20.1
      domain_name: lab.astr0rack.net
      start: 10.0.20.10
      stop: 10.0.20.200
  - name: eth4
    type: ethernet
    desc: LABC2
    mac: a6:3e:71:ea:29:0d
    ipv4_addr: 10.0.255.1/24
    dhcp:
      subnet: 10.0.255.0/24
      gw: 10.0.255.1
      dns_servers:
        - 10.0.255.1
      domain_name: lab.astr0rack.net
      start: 10.0.255.150
      stop: 10.0.255.200
      static_mappings:
        - name: c2
          mac: 1a:f4:ef:e2:f6:fe
          ipv4: 10.0.255.100
  - name: eth5
    type: ethernet
    desc: TEMPLATENET
    mac: 86:bf:48:80:96:3b
    ipv4_addr: 10.0.1.1/24
    dhcp:
      subnet: 10.0.1.0/24
      gw: 10.0.1.1
      dns_servers:
        - 1.1.1.1
      domain_name: lab.astr0rack.net
      start: 10.0.1.10
      stop: 10.0.1.200
  - name: eth7
    type: ethernet
    desc: DEVNET 
    mac: 56:e0:3a:73:1a:1f
    ipv4_addr: 10.100.0.1/24
    dhcp:
      subnet: 10.100.0.0/24
      gw: 10.100.0.1
      dns_servers:
        - 10.100.0.1
      domain_name: lab.astr0rack.net
      start: 10.100.0.10
      stop: 10.100.0.200
  - name: eth8
    type: ethernet
    desc: SWAN
    mac: d2:dc:b9:42:47:4f 
    ipv4_addr: 192.168.230.1/24
    dhcp:
      subnet: 192.168.230.0/24
      gw: 192.168.230.1
      dns_servers:
        - 192.168.230.1
      domain_name: lab.astr0rack.net
      start: 192.168.230.10
      stop: 192.168.230.200
static_routes:
  - subnet: 0.0.0.0/0
    dhcp_interface: eth0
source_nat:
  - outbound_interface: eth0
    source_address: 10.0.0.0/8
    translation_address: masquerade
  - outbound_interface: eth0
    source_address: 192.168.230.0/24
    translation_address: masquerade
destination_nat:
  - inbound_interface: eth0
    destination_port: 22000
    protocol: tcp_udp
    translation_address: 10.100.0.3
  - inbound_interface: eth0
    destination_port: 3393
    protocol: tcp
    translation_address: 10.100.0.3
    translation_port: 3389
  - inbound_interface: eth0
    destination_port: 3396
    protocol: tcp
    translation_address: 10.100.0.6
    translation_port: 3389
  - inbound_interface: eth0
    destination_port: 3397
    protocol: tcp
    translation_address: 10.100.0.7
    translation_port: 3389
dns:
  search_domain: lab.astr0rack.net
  servers:
    - 1.1.1.1
    - 1.0.0.1
  host_name: vyos-core
  domain_name: lab.astr0rack.net
ntp:
  listen_address: 0.0.0.0
  servers:
    - 0.pool.ntp.org
    - 1.pool.ntp.org
    - 2.pool.ntp.org
  allowed_clients:
    - 10.0.0.0/8
ssh:
  disable_password_authentication: true
  disable_host_validation: true
  listen_address: 0.0.0.0
firewall_global_options:
  - name: all-ping
    setting: enable
  - name: state-policy related action
    setting: accept
  - name: state-policy established action
    setting: accept
  - name: state-policy invalid action
    setting: drop
firewall_address_groups:
  - name: dc-01
    ip: 10.0.0.50
    groups:
      - dc-01
      - lab-dc
  - name: dc-02
    ip: 10.0.0.51
    groups:
      - dc-02
      - lab-dc
  - name: dns-01
    ip: 10.0.10.10
    groups:
      - dns-01
      - lab-server
  - name: web-01
    ip: 10.0.10.20
    groups:
      - web-01
      - lab-server
  - name: c2
    ip: 10.0.255.100
    groups:
      - c2
      - lab-c2
  - name: external-gw
    ip: 192.168.55.1
    groups:
      - external-gw
      - lab-external
  - name: external-pm
    ip: 192.168.55.2
    groups:
      - external-pm
      - lab-external
      - lab-reachable-tailscale
  - name: external-vyos
    ip: 192.168.55.3
    groups:
      - external-vyos
      - lab-external
      - lab-reachable-tailscale
  - name: rack-space
    ip: 10.64.1.2-10.64.1.3
    groups:
      - rack-ip-space
  - name: lab-space
    ip: 10.0.0.0-10.0.255.255
    groups:
      - lab-ip-space
  - name: slab-space
    ip: 192.168.230.0-192.168.230.255
    groups:
      - lab-ip-space
  - name: tailscale-dns
    ip: 100.100.100.100
    groups:
      - tailscale-dns
  - name: dev-space
    ip: 192.168.55.4-192.168.55.254
    groups:
      - dev-space
  - name: dev-ip-space
    ip: 10.100.0.2-10.100.0.254
    groups:
      - dev-ip-space
firewall_zones:
  - name: external-rack
    description: rack
    interfaces:
      - eth0
  - name: external-tailscale
    description: lab
    interfaces:
      - tailscale0
  - name: internal-lab
    description: lab
    interfaces:
      - eth1
      - eth2
      - eth3
      - eth4
      - eth8
  - name: template-net
    description: template
    interfaces:
      - eth5
  - name: dev-net
    description: dev-net 
    interfaces:
      - eth7
  - name: local
    description: local
    interfaces:
      - local-zone
firewall_rules:
  - name: rack_to_dev_ipv4
    assignments:
      - from: external-rack
        to: dev-net
    ipv4:
      - protocol: tcp_udp
        destination_port: 22000
        destination_address: 10.100.0.3
        action: accept
      - protocol: tcp
        destination_port: 3389
        action: accept
      - protocol: all
        action: drop
  - name: rack_to_local_ipv4
    assignments:
      - from: external-rack
        to: local
    ipv4:
      - protocol: tcp
        destination_port: 22
        action: accept
      - protocol: tcp
        destination_port: 53
        action: accept
      - protocol: udp
        destination_port: 53
        action: accept
      - protocol: udp
        destination_port: 41641
        action: accept
      - protocol: icmp
        action: accept
      - protocol: all
        action: drop
  - name: lab_to_rack_ipv4
    assignments:
      - from: internal-lab
        to: external-rack
    ipv4:
      - source_group:
          type: address
          name: lab-ip-space
        destination_group:
          type: address
          name: rack-ip-space
        protocol: all
        action: drop
      - source_group:
          type: address
          name: lab-ip-space
        protocol: tcp_udp
        action: accept
      - protocol: all
        action: drop
  - name: dev_to_rack_ipv4
    assignments:
      - from: dev-net
        to: external-rack
    ipv4:
      - source_group:
          type: address
          name: dev-ip-space
        destination_group:
          type: address
          name: external-pm 
        destination_port: 443
        protocol: tcp
        action: accept 
      - source_group:
          type: address
          name: dev-ip-space
        destination_group:
          type: address
          name: rack-ip-space
        protocol: all
        action: accept 
      - source_group:
          type: address
          name: dev-ip-space
        destination_group:
          type: address
          name: lab-ip-space
        protocol: all
        action: drop
      - protocol: tcp_udp
        action: accept
      - protocol: all
        action: drop
  - name: local_to_rack_ipv4
    assignments:
      - from: local
        to: external-rack
    ipv4:
      - destination_group:
          type: address
          name: lab-external
        protocol: tcp_udp
        action: accept
      - destination_group:
          type: address
          name: lab-external
        protocol: icmp
        action: accept
      - destination_group:
          type: address
          name: rack-ip-space
        protocol: all
        action: drop
      - protocol: tcp_udp
        action: accept
      - protocol: icmp
        action: accept
      - protocol: all
        action: drop
  - name: local_to_lab_ipv4
    assignments:
      - from: local
        to: internal-lab
    ipv4:
      - protocol: all
        action: accept
  - name: lab_to_local_ipv4
    assignments:
      - from: internal-lab
        to: local
      - from: dev-net
        to: local
    ipv4:
      - protocol: udp
        destination_port: 53
        action: accept
      - protocol: udp
        destination_port: 123
        action: accept
      - protocol: all
        action: drop
  - name: tailscale_to_lab_ipv4
    assignments:
      - from: external-tailscale
        to: internal-lab
    ipv4:
      - protocol: all
        action: accept
  - name: tailscale_to_external_rack_ipv4
    assignments:
      - from: external-tailscale
        to: external-rack
    ipv4:
      - destination_group:
          type: address
          name: external-pm
        protocol: tcp
        destination_port: 22
        action: accept
      - destination_group:
          type: address
          name: external-pm
        protocol: tcp
        destination_port: 443
        action: accept
      - destination_group:
          type: address
          name: external-pm
        protocol: tcp
        destination_port: 5432
        action: accept
      - destination_group:
          type: address
          name: dev-space
        protocol: tcp_udp
        action: accept
      - destination_group:
          type: address
          name: lab-reachable-tailscale
        protocol: icmp
        action: accept
      - protocol: all
        action: drop
  - name: tailscale_to_local_ipv4
    assignments:
      - from: external-tailscale
        to: local
    ipv4:
      - destination_group:
          type: address
          name: external-vyos
        protocol: tcp_udp
        destination_port: 53
        action: accept
      - destination_group:
          type: address
          name: external-vyos
        protocol: tcp
        destination_port: 22
        action: accept
      - protocol: icmp
        action: accept
      - protocol: all
        action: drop
  - name: local_to_tailscale_ipv4
    assignments:
      - from: local
        to: external-tailscale
    ipv4:
      - destination_group:
          type: address
          name: tailscale-dns
        protocol: tcp_udp
        destination_port: 53
        action: accept
      - protocol: icmp
        action: accept
      - protocol: all
        action: drop
  - name: tailscale_to_template_net_ipv4
    assignments:
      - from: external-tailscale
        to: template-net
    ipv4:
      - protocol: tcp
        destination_port: 22
        action: accept
      - protocol: icmp
        action: accept
      - protocol: all
        action: drop
  - name: template_net_to_tailscale_ipv4
    assignments:
      - from: template-net
        to: external-tailscale
    ipv4:
      - protocol: tcp_udp
        action: accept
      - protocol: icmp
        action: accept
      - protocol: all
        action: drop
  - name: template_to_rack_ipv4
    assignments:
      - from: template-net
        to: external-rack
    ipv4:
      - destination_group:
          type: address
          name: rack-ip-space
        protocol: all
        action: drop
      - source_group:
          type: address
          name: lab-ip-space
        protocol: tcp_udp
        action: accept
      - protocol: all
        action: drop
containers:
  - name: bind9
    image: docker.io/ubuntu/bind9:latest
    network: allow-host-networks
    environment:
      - key: BIND9_USER
        value: root
    volumes:
      - name: config
        destination: /etc/bind
        source: /config/user-data/bind9/etc
      - name: cache
        destination: /var/cache/bind
        source: /config/user-data/bind9/cache
      - name: records
        destination: /var/lib/bind
        source: /config/user-data/bind9/records
