---
- name: Implement rack network
  community.docker.docker_network:
    name: rack

- name: Create watchtower etc directory
  ansible.builtin.file:
    path: /etc/watchtower
    state: directory
    mode: '0755'

- name: Create watchtower configuration directory
  ansible.builtin.file:
    path: /etc/compose/watchtower
    state: directory
    mode: '0755'

- name: Copy the compose file
  ansible.builtin.template:
    src: watchtower.yaml
    dest: /etc/compose/watchtower/docker-compose.yaml
    mode: "0600"

- name: Create keycloak data volume
  community.docker.docker_volume:
    name: keycloak_db_vol

- name: Create keycloak configuration directory
  ansible.builtin.file:
    path: /etc/compose/keycloak
    state: directory
    mode: '0755'

- name: Copy the compose file
  ansible.builtin.template:
    src: keycloak.yaml
    dest: /etc/compose/keycloak/docker-compose.yaml
    mode: '0600'

- name: Create postgres data volume
  community.docker.docker_volume:
    name: postgres_data_vol

- name: Create postgres configuration directory
  ansible.builtin.file:
    path: /etc/compose/postgres
    state: directory
    mode: '0755'

- name: Copy the compose file
  ansible.builtin.template:
    src: postgres.yaml
    dest: /etc/compose/postgres/docker-compose.yaml
    mode: '0600'

- name: Create caddy data volume
  community.docker.docker_volume:
    name: caddy_data_vol

- name: Create caddy configuration directory
  ansible.builtin.file:
    path: /etc/compose/caddy
    state: directory
    mode: '0755'

- name: Copy the compose file
  ansible.builtin.template:
    src: caddy.yaml
    dest: /etc/compose/caddy/docker-compose.yaml
    mode: '0600'

- name: Create caddy configuration directory
  ansible.builtin.file:
    path: /etc/caddy
    state: directory
    mode: '0755'

- name: Copy the Caddyfile
  ansible.builtin.copy:
    src: Caddyfile
    dest: /etc/caddy/Caddyfile
    mode: "0644"

- name: Configure pveproxy
  ansible.builtin.blockinfile:
    create: true
    path: /etc/default/pveproxy
    block: |
      ALLOW_FROM="172.16.0.0/12"
      DENY_FROM="all"
      POLICY="allow"
    mode: "0644"
  notify: Restart pveproxy

- name: Start caddy
  community.docker.docker_compose:
    project_src: /etc/compose/caddy

- name: Start keycloak
  community.docker.docker_compose:
    project_src: /etc/compose/keycloak

- name: Start postgres
  community.docker.docker_compose:
    project_src: /etc/compose/postgres

- name: Start watchtower
  community.docker.docker_compose:
    project_src: /etc/compose/watchtower
