---
- name: Change the hostname to our standard
  hostname:
    name: '{{ ansible_host }}'

- name: "Add proxmox /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: '.*proxmox.*$'
    line: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} proxmox.lab.astr0rack.net proxmox auth.lab.astr0rack.net"
    state: present

- name: Make sure proxmox enterprise repo is disabled
  copy:
    content: ""
    dest: /etc/apt/sources.list.d/pve-enterprise.list
    force: yes

- name: Setup proxmox repo
  copy:
    content: "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
    dest: /etc/apt/sources.list.d/pve-no-subscription.list
    force: no
  register: fresh_install

- name: Get Proxmox repo signing key
  ansible.builtin.get_url:
    url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
    dest: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg

- name: Enable repos
  ansible.builtin.lineinfile:
    path: '/etc/apt/sources.list'
    regexp: '^deb http://deb.debian.org/debian/ bookworm main'
    line: 'deb http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware'

- name: Update system
  apt:
    upgrade: full
    update_cache: yes
  when: fresh_install.changed

- name: Install pve kernel packages
  apt:
    name:
      - pve-kernel-6.2
      - pve-headers
      - dkms
    state: present
    update_cache: true
  notify:
    - Disable SB Validation

- name: Install pve packages
  apt:
    name:
      - vim
      - tmux
      - zsh
      - sudo
      - wget
      - unattended-upgrades
      - docker.io
      - docker-compose
      - python3-docker
      - python3-pip
      - hashcat
      - htop
      - nvidia-detect
      - nvidia-driver 
      - openvswitch-switch
      - proxmox-ve
    state: present
    update_cache: true

- name: Remove debian kernel
  apt:
    name:
      - linux-image-amd64
      - 'linux-image-6.1*'
      - os-prober
    state: absent

- name: Enable Docker
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: yes

- name: Add ghactions user
  ansible.builtin.user:
    name: ghactions
    comment: GitHub Actions User
    groups: sudo
    password: "{{ ghactions_user_hash }}"
    shell: /bin/bash

- name: Add astr0n8t user
  ansible.builtin.user:
    name: astr0n8t
    comment: astr0n8t
    groups: sudo
    password: "{{ astr0n8t_user_hash }}"
    shell: /bin/bash

- name: Add ghactions ssh key
  ansible.posix.authorized_key:
    user: ghactions
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH8ts84bR4nen8+Kk6I48MDkg8WA+gnuoUFuCmG9B6Xg ghactions@github.com"

- name: Add primary ssh key
  ansible.posix.authorized_key:
    user: astr0n8t
    state: present
    key: "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIFEhLIyleqCaN3lEJ77AYc/q1uZlqsDJ4PKhBu0dXUa7AAAABHNzaDo= astr0n8t@primary.yubikey"

- name: Add secondary ssh key
  ansible.posix.authorized_key:
    user: astr0n8t
    state: present
    key: "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIHKBaozeIJ+Gz7+J2dK2VrQPaWerVWH8a9xYIjhvygLmAAAABHNzaDo= astr0n8t@secondary.yubikey"

- name: Add mobile ssh key
  ansible.posix.authorized_key:
    user: astr0n8t
    state: present
    key: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGwVUk4wWGiJQjd7P2z2XZ9Gzia0GTy2faoAnyWVEF+jweR2q16C75oIzZbgE1mN3oc4BD9z8rIA1ElXapGI77I= astr0n8t@mobile"

- name: Copy sshd config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
  register: sshd

- name: Restart sshd
  ansible.builtin.systemd:
    name: ssh.service
    state: restarted
    enabled: yes
  when: sshd.changed

- name: Enable all updates automatically
  ansible.builtin.lineinfile:
    path: '/etc/apt/apt.conf.d/50unattended-upgrades'
    regexp: ^        "${distro_id}:${distro_codename}-updates";'
    line: '        "${distro_id}:${distro_codename}-updates";'
    insertafter: "Unattended-Upgrade::Allowed-Origins {"

- name: Enable all proposed updates automatically
  ansible.builtin.lineinfile:
    path: '/etc/apt/apt.conf.d/50unattended-upgrades'
    regexp: '^        "${distro_id}:${distro_codename}-proposed";'
    line: '        "${distro_id}:${distro_codename}-proposed";'
    insertafter: "Unattended-Upgrade::Allowed-Origins {"

- name: Enable all backport updates automatically
  ansible.builtin.lineinfile:
    path: '/etc/apt/apt.conf.d/50unattended-upgrades'
    regexp: '^        "${distro_id}:${distro_codename}-backport";'
    line: '        "${distro_id}:${distro_codename}-backport";'
    insertafter: "Unattended-Upgrade::Allowed-Origins {"

- name: Copy discord notify script
  template:
    src: discord-init.sh
    dest: /usr/bin/discord_status_notify
    mode: "0755"

- name: Copy discord notifier
  copy:
    src: discord-notif.service
    dest: /etc/systemd/system/
    mode: "0644"

- name: Enable discord-notif 
  ansible.builtin.systemd:
    name: discord-notif.service
    daemon_reload: yes
    enabled: yes

- name: Copy discord notifier
  copy:
    src: 80-shutdown-on-battery.rules
    dest: /etc/udev/rules.d/80-shutdown-on-battery.rules
    mode: "0644"

