---
- name: Include secrets from environment
  include_tasks: 
    file: env.yml
    apply:
      tags:
        - env
  tags:
    - env
    - never
- name: Include secrets from bitwarden
  include_tasks: 
    file: bw.yml
    apply:
      tags:
        - bw
  tags:
    - bw
    - never
- name: Apply general setup and hardening
  include_tasks: 
    file: general_setup.yml
    apply:
      tags:
        - setup
  tags:
    - setup
- name: Configure Proxmox network interfaces
  include_tasks:
    file: setup_nics.yml
    apply:
      tags:
        - setup-nics
  tags:
    - setup-nics
- name: Setup Proxmox Docker containers
  include_tasks:
    file: deploy_containers.yml
    apply:
      tags:
        - containers
  tags:
    - containers
- name: Configure Proxmox for use with Terraform
  include_tasks:
    file: setup_terraform.yml
    apply:
      tags:
        - setup-terraform
  tags:
    - setup-terraform
- name: Configure Proxmox for use with Keycloak
  include_tasks:
    file: setup_keycloak.yml
    apply:
      tags:
        - setup-keycloak
  tags:
    - setup-keycloak
- name: Patch proxmox functions
  include_tasks: 
    file: patch_proxmox.yml
    apply:
      tags:
        - patch
  tags:
    - patch
- name: Configure Proxmox Pools and Permissions
  include_tasks: 
    file: setup_perms.yml
    apply:
      tags:
        - perms
  tags:
    - perms
- name: Configure VyOS VM Template
  include_tasks:
    file: create_vyos_image.yml
    apply:
      tags:
        - vyos-image
  tags:
    - vyos-image
