---
- name: Configure roles
  ansible.builtin.shell: |
    pveum role add TerraformProv -privs "Datastore.Allocate \
    Datastore.AllocateSpace Datastore.AllocateTemplate Datastore.Audit \
    Group.Allocate Permissions.Modify Pool.Allocate Pool.Audit SDN.Allocate \
    SDN.Audit SDN.Use Sys.Audit Sys.Console Sys.Modify VM.Allocate VM.Audit \
    VM.Backup VM.Clone VM.Config.CDROM VM.Config.CPU VM.Config.Cloudinit \
    VM.Config.Disk VM.Config.HWType VM.Config.Memory VM.Config.Network \
    VM.Config.Options VM.Console VM.Migrate VM.Monitor VM.PowerMgmt \
    VM.Snapshot VM.Snapshot.Rollback"
    pveum user add terraform@pve --password "{{ terraform_proxmox_password }}"
    pveum aclmod / -user terraform@pve -role TerraformProv
  register: command
  changed_when: "command.rc == 0"
