version: '3.4'

services:
  postgres:
    container_name: postgres
    image: docker.io/library/postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: terraform
      POSTGRES_DB: terraform
      POSTGRES_PASSWORD: {{ postgres_password }}
    volumes:
      - "postgres_data_vol:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  postgres_data_vol:
    external: true

