- hosts: all
  name: Create VyOS image
  tags: [ always ]
  become: true
  tasks:
    - name: Download latest VyOS Build
      ansible.builtin.get_url:
        url: https://github.com/astr0n8t/vyos-tailscale-gha/releases/download/v1.4-rolling-202306092357/vyos-qemu-1.4-rolling-202306092357-amd64.qcow2
        dest: /tmp/vyos-qemu-latest-amd64.qcow2

    - name: Create new VM to serve as template
      ansible.builtin.shell: |
        qm destroy 999
        qm create 999 --name vyos-1.4-rolling-cloudinit --memory 1024 --bios ovmf 
        qm importdisk 999 /tmp/vyos-qemu-latest-amd64.qcow2 data --format qcow2
        qm set 999 --scsi0 data:vm-999-disk-0
        qm set 999 --boot c --bootdisk scsi0
        qm template 999

    - name: Remove disk image on tmp
      ansible.builtin.file:
        path: /tmp/vyos-qemu-latest-amd64.qcow2
        state: absent

