- hosts: all
  name: Add Terraform role/user
  tags: [ always ]
  become: true
  tasks:

    - name: Configure roles
      ansible.builtin.shell: |
        pveum role add TerraformProv -privs "Datastore.AllocateSpace Datastore.Audit Pool.Allocate Sys.Audit Sys.Console Sys.Modify VM.Allocate VM.Audit VM.Clone VM.Config.CDROM VM.Config.Cloudinit VM.Config.CPU VM.Config.Disk VM.Config.HWType VM.Config.Memory VM.Config.Network VM.Config.Options VM.Migrate VM.Monitor VM.PowerMgmt"
        pveum user add terraform@pve --password "{{ terraform_proxmox_password }}"
        pveum aclmod / -user terraform@pve -role TerraformProv
      vars:
        terraform_proxmox_password: "{{ lookup('community.general.bitwarden', 'terraform-proxmox-credentials', field='password')[0] }}"

