all:
  hosts:
    proxmox:
      ansible_user: ghactions
      ansible_host: proxmox.lab.astr0rack.net
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_become_password: "{{ lookup('ansible.builtin.env', 'ANSIBLE_BECOME_PASSWORD') }}"
    vyos:
      ansible_user: vyos
      ansible_host: vyos.lab.astr0rack.net
      ansible_connection: network_cli
      ansible_network_os: vyos
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_become_password: "{{ lookup('ansible.builtin.env', 'ANSIBLE_BECOME_PASSWORD') }}"
