- hosts: vyos
  name: Setup Bind9 DNS server
  tags: [ always ]
  become: true
  gather_facts: false
  tasks:

    - name: set facts for ansible ssh
      set_fact:
        ansible_connection: ssh
        ansible_user: vyos

    - name: Create bind9 config directory
      file:
        path: /config/user-data/bind9/etc
        state: directory
        mode: '0775'
        owner: root
        group: vyattacfg
        recurse: yes

    - name: Copy the named.conf
      template:
        src: named.conf
        dest: /config/user-data/bind9/etc/
        owner: root
        group: vyattacfg
        mode: "0660"
      vars:
        lab_astr0rack_dns_key: "{{ lookup('community.general.bitwarden', 'ansible-vyos-bind9-lab-astr0rack-key', field='password')[0] }}"

    - name: Copy the Zone file
      copy:
        src: lab-astr0rack-net.zone
        dest: /config/user-data/bind9/etc/
        owner: root
        group: vyattacfg
        mode: "0660"

    - name: Create bind9 cache directory
      file:
        path: /config/user-data/bind9/cache
        state: directory
        mode: '0775'
        owner: root
        group: vyattacfg

    - name: Create bind9 record directory
      file:
        path: /config/user-data/bind9/records
        state: directory
        mode: '0775'
        owner: root
        group: vyattacfg

    - name: set facts for network connection
      set_fact:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: vyos.vyos.vyos
        ansible_user: vyos

    - name: configure and start bind9
      vyos.vyos.vyos_config:
        lines:
          - set container name bind9 image 'docker.io/ubuntu/bind9:latest'
          - set container name bind9 allow-host-networks
          - set container name bind9 environment BIND9_USER value 'root'
          - set container name bind9 volume config destination '/etc/bind'
          - set container name bind9 volume config source '/config/user-data/bind9/etc'
          - set container name bind9 volume cache destination '/var/cache/bind'
          - set container name bind9 volume cache source '/config/user-data/bind9/cache'
          - set container name bind9 volume records destination '/var/lib/bind'
          - set container name bind9 volume records source '/config/user-data/bind9/records'

    - name: Pull bind9 image and start container 
      vyos.vyos.vyos_command:
        commands:
        - update container image bind9
        - restart container bind9
