- hosts: vyos
  name: Setup Tailscale
  tags: [ always ]
  become: true
  gather_facts: false
  tasks:

    - name: Check tailscale status
      vyos.vyos.vyos_command:
        commands:
          - tailscale status
      register: tailscale_status

    - name: Login to tailscale and start
      vyos.vyos.vyos_command:
        commands:
        - "sudo tailscale login  --auth-key={{ lookup('community.general.bitwarden', 'ansible-vyos-tailscale-auth-key', field='password')[0] }}"
        - sudo tailscale up --advertise-routes=10.0.0.0/16,192.168.55.2/32,192.168.55.3/32
      when: "'Logged out.' in tailscale_status.stdout"
