name: "Ansible Lint"

on:
  pull_request:
    paths:
      - 'ansible/**'
  workflow_dispatch:

jobs:
  ansible-lint:
    name: "Ansible Lint"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lab-astr0rack-net/ansible:latest
    defaults:
      run:
        working-directory: ansible
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6
        with:
          path: "ansible/"

