name: "Proxmox Ansible Configuration Apply"

on:
  push:
    branches:
      - main
    paths:
      - 'ansible/roles/proxmox/**'
      - 'ansible/playbooks/proxmox.yml'
  workflow_dispatch:

jobs:
  ansible:
    name: "Ansible"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lab-astr0rack-net/ansible:latest
      options: --cap-add=NET_ADMIN --cap-add=NET_RAW --dns=1.1.1.1 --dns=100.100.100.100
      volumes:
        - /var/lib:/var/lib
        - /dev/net/tun:/dev/net/tun
    defaults:
      run:
        working-directory: ansible
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup ssh key
        env:
          SSH_KEY:  ${{ secrets.ANSIBLE_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 400 ~/.ssh/id_ed25519

      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Ping proxmox
        run: ansible --ssh-extra-args '"-o StrictHostKeyChecking=accept-new"' -i inventory.yaml -m ping proxmox

      - name: Run the proxmox playbook
        env:
          ANSIBLE_BECOME_PASSWORD:  ${{ secrets.ANSIBLE_BECOME_PASSWORD }}
        run: ansible-playbook playbooks/proxmox.yaml

      - name: Logout of Tailscale
        id: ts-logout
        run: sudo tailscale logout
