name: "Ansible Lint"

on:
  pull_request:
    paths:
      - 'ansible/**'
  workflow_dispatch:


jobs:
  ansible-lint:
    name: "Ansible Lint"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lab-astr0rack-net/ansible:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run ansible-lint
        env:
          ANSIBLE_ROLES_PATH: 'ansible/roles:$ANSIBLE_HOME/roles:/usr/share/ansible/roles:/etc/ansible/roles'
        run: |
          git config --global --add safe.directory /__w/core/core
          ansible-lint --exclude './ansible/roles/proxmox/files' --exclude './ansible/roles/proxmox/templates' --exclude './ansible/roles/vyos/files' --exclude './ansible/roles/vyos/templates' ansible/
