name: "Terraform Apply"

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lab-astr0rack-net/terraform:latest
      options: --cap-add=NET_ADMIN --cap-add=NET_RAW
      volumes:
        - /var/lib:/var/lib
        - /dev/net/tun:/dev/net/tun
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Download Tailscale
        shell: bash
        id: download
        env:
          VERSION: '1.14.0'
        run: |
          MINOR=$(echo $VERSION | awk -F '.' {'print $2'})
          if [ $((MINOR % 2)) -eq 0 ]; then
            URL="https://pkgs.tailscale.com/stable/tailscale_${VERSION}_amd64.tgz"
          else
            URL="https://pkgs.tailscale.com/unstable/tailscale_${VERSION}_amd64.tgz"
          fi
          curl $URL -o tailscale.tgz
          tar -C ${HOME} -xzf tailscale.tgz
          rm tailscale.tgz
          TSPATH=${HOME}/tailscale_${VERSION}_amd64
          sudo mv "${TSPATH}/tailscale" "${TSPATH}/tailscaled" /usr/bin

      - name: Debug tailscaled
        run: sudo tailscaled
          
      - name: Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: "& tail -f ~/tailscaled.log &"

      - name: Terraform Init
        env:
          PG_CONN_STR: ${{ secrets.TF_POSTGRES_CRED }}
        id: init
        run: terraform init -backend-config="conn_str=$${PG_CONN_STR}"
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        if: (github.ref == 'refs/heads/main' ) && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        env:
          TF_VAR_pm_password:  ${{ secrets.TF_PROXMOX_CRED }}
        run: terraform apply -auto-approve -input=false -var-file=development.tfvars

      - name: Logout of Tailscale
        id: ts-logout
        run: sudo tailscale logout
